train_logs_epoch = 'epoch'
train_logs_start_time = 'start_time'
train_logs_end_time = 'end_time'
train_logs_data = 'data'
train_logs_start_index = 'data_start_index'

class TrainLogsMetrics:
    train_loss = 'train_loss'
    train_loss_policy = 'train_loss_policy'
    train_loss_value = 'train_loss_value'
    train_accuracy_policy = 'train_accuracy_policy'
    validation_loss = 'validation_loss'
    validation_loss_policy = 'validation_loss_policy'
    validation_loss_value = 'validation_loss_value'
    validation_accuracy_policy = 'validation_accuracy_policy'
